build-sys: Remove unneeded workaround
This is causing a build breakage when libmsi-1.0.pc isn't installed yet:

$ make
  VALAC    libcommon_a_vala.stamp
  CC       tools/wixl/libcommon_a-util.o
  AR       libcommon.a
  VALAC    wixl_vala.stamp
error: Package `libmsi-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
Makefile:1110: recipe for target 'wixl_vala.stamp' failed
make: *** [wixl_vala.stamp] Error 1